---
- name: execute roles
  hosts: 127.0.0.1
  connection: local
  gather_facts: true
  become: true
  

  roles:
    - role: install_apache
    - role: install_mariadb
    # Nur ein Kommentar...

  
       